// Level layouts ported from levels/Level1-12.java
// w=wall d=dirt c=dot o=donut g=ghost pepper l=lava p=player spawn m=monster spawn
export const LEVELS = [
  { // Level 1
    enemies: ["blind"],
    layout: [
      "wwwwwwwwww",
      "wccccccccw",
      "wcddmdddcw",
      "wcddddddcw",
      "wcmdccddcw",
      "wcddccdmcw",
      "wcddddddcw",
      "wcddpdddcw",
      "wccccccccw",
      "wwwwwwwwww",
    ],
  },
  { // Level 2
    enemies: ["standard"],
    layout: [
      "wwwwwwwwww",
      "wccccccccw",
      "wcddmdddcw",
      "wcddddddcw",
      "wcmdllddcw",
      "wcddlldmcw",
      "wcddddddcw",
      "wcddpdddcw",
      "wccccccccw",
      "wwwwwwwwww",
    ],
  },
  { // Level 3
    enemies: ["standard","standard"],
    layout: [
      "wwwwwwwwww",
      "wccccccccw",
      "wcodmdddcw",
      "wcddddddcw",
      "wcmdccddcw",
      "wcddccdmcw",
      "wcddddddcw",
      "wcddpdddcw",
      "wccccccccw",
      "wwwwwwwwww",
    ],
  },
  { // Level 4
    enemies: ["blind","blind","blind","blind","blind","blind","blind"],
    layout: [
      "wwwwwwwwww",
      "wccccccccw",
      "wcodmdddcw",
      "wcddddddcw",
      "wcmdccddcw",
      "wcddccdmcw",
      "wcddddddcw",
      "wcddpdddcw",
      "wccccccccw",
      "wwwwwwwwww",
    ],
  },
  { // Level 5
    enemies: ["standard","standard","standard"],
    layout: [
      "wwwwwwwwww",
      "wocccccccw",
      "wcwwmmwwcw",
      "wcwwddwwcw",
      "wcmdccdmcw",
      "wcmdccdmcw",
      "wcwwddwwcw",
      "wcwwdpwwcw",
      "wccccccccw",
      "wwwwwwwwww",
    ],
  },
  { // Level 6
    enemies: ["all seeing"],
    layout: [
      "wwwwwwwwww",
      "wocccccccw",
      "wwwwwmwwcw",
      "wcccddddcw",
      "wwwwwcwwcw",
      "wcwdccdmcw",
      "wcwdwdwwcw",
      "wcwdwpwwcw",
      "wccccdcccw",
      "wwwwwwwwww",
    ],
  },
  { // Level 7
    enemies: ["all seeing","standard"],
    layout: [
      "wwwwwwwwww",
      "wccmmdccdw",
      "wcwwwcwwcw",
      "wwwcccwwcw",
      "wcccwddmcw",
      "wcwwwcwmlw",
      "wcwlwcwwww",
      "wmmccdwddw",
      "wccwoccpdw",
      "wwwwwwwwww",
    ],
  },
  { // Level 8
    enemies: ["all seeing","all seeing"],
    layout: [
      "wwwwwwwwww",
      "wclccocccw",
      "wclwmddmcw",
      "wmddddwdcw",
      "wdmdlclwcw",
      "wcwdwcdmcw",
      "wcwdddwwww",
      "wmwwwddddw",
      "wocccdwdpw",
      "wwwwwwwwww",
    ],
  },
  { // Level 9
    enemies: ["standard","standard","standard"],
    layout: [
      "wwwwwwwwww",
      "wccccccccw",
      "wpwwwwwwcw",
      "wcwccdcwcw",
      "wdwdwccwcw",
      "wcwcwcdwcw",
      "wcwcwllwcw",
      "wmwdwwwwdw",
      "wmcccdcwgw",
      "wwwwwwwwww",
    ],
  },
  { // Level 10
    enemies: ["blind","blind","blind","blind","blind","blind"],
    layout: [
      "wwwwwwwwww",
      "wcmcccccmw",
      "wcwwwcwwcw",
      "wcdccdccdw",
      "wcwwwmwwcw",
      "wcccdccdcw",
      "wcwwwcwwcw",
      "wccdcdccdw",
      "wwpwdwgwdw",
      "wwwwwwwwww",
    ],
  },
  { // Level 11
    enemies: ["standard","standard","standard","blind","blind"],
    layout: [
      "wwwwwwwwww",
      "wcmccccwmw",
      "wcwcwwwwcw",
      "wcwcwowddw",
      "wcwcwwwwcw",
      "wcwcdcdccw",
      "wcccwwwccw",
      "wcwwwdccdw",
      "wdpcdcwcgw",
      "wwwwwwwwww",
    ],
  },
  { // Level 12
    enemies: ["standard","standard","all seeing","blind"],
    layout: [
      "wwwwwwwwww",
      "wcmccccccw",
      "wcwcwwwwmw",
      "wcwccdcwgw",
      "wdccwwwwcw",
      "wcwcdccdcw",
      "wcwccwlwcw",
      "wwwwcwwwdw",
      "wcpccdccdw",
      "wwwwwwwwww",
    ],
  },
];
